services:
    typing:
        hostname: typing
        container_name: typing
        image: typing
        ports:
            - 80:80
            - 443:443
        volumes:
            - ../nginx/conf.prod.d/:/etc/nginx/conf.d/
            - ./.ssl/ca.crt:/etc/ssl/ca.crt
            - ./.ssl/private:/etc/.ssl/private/
        build:
            context: ../../
            dockerfile: Dockerfile
